### PR TITLE
Add field options list command

### PR DESCRIPTION
**Pull request by mjasion**
This change adds the `field-list-options` command to list options in Project SingleSelect and Iteration fields.

For the SingleSelect field, it outputs the `ID` and `Name`
```
ID        Name
e78f01e0  Small - 1 week
3ed06828  Medium - 2 weeks
85f5c5b0  Large - 3 weeks
a040e085  Extra Large - 4 weeks
10707151  Entire Quarter - 4 week+
```

For Iteration Field, it outputs more columns: 

```
ID        Title    Start Date  Duration  Completed
9c34b0ca  Week 1   2022-11-29  7         true
...
e7c3a604  Week 14  2023-02-28  7         true
dd6221d6  Week 15  2023-03-07  7         true
69447a4f  Week 16  2023-03-14  7         true
5349eea9  Week 17  2023-03-21  7
f9369bb2  Week 18  2023-03-28  7
79cece39  Week 19  2023-04-04  7
...
```

## The use case

The use case for this command is to improve automation workflow for Projects. [GitHub Project Docs](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions#example-workflow-authenticating-with-a-github-app) are showing large GQL query to update specific field. For setting the Itration Fields, the query will take much work to maintain. So your projects have improved a lot, which is why I contributed. :-) 

This is the first part of the changes I would like to add. The next will be updating the field values in Project Items(e.g. automate changes of the Sprint week)

### CODE REVIEW

**Comment by mjasion** [comment]
Hi @mntlty, Thanks for the response :-) 

Our case where we are missing the GitHub project is automation on setting custom project fields, like an iteration on the item. I have two use cases for the Iteration fields:

1. When we add a PR to the project(not connected to any issue), we forget to set a `Week` for the actual iteration. It is not visible in the options when the PR is being created. So this is the first automation: **set the current iteration to the item.**. We have a board that shows our items with the `@current` iteration. 

2. The second thing which should be easy to automate is: **to change iteration from `@previous` to `@current` for not finished items.** 
We want to prepare a workflow that automatically walks from the items and sets the Iteration to the current week. This could be triggered by a schedule, or by dispatch. Maybe GitHub developers will add a button for this in the future. IDK 🙃 

To set the iteration on the item, I need:
- Option ID from a given operation of the option, which is `@current` (first, not completed Iteration option)
- item id 

In the [docs](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions#example-workflow-authenticating-with-a-github-app) example of setting fields in an item is long:

<details><summary>Example</summary>
<p>

```yml 
      - name: Set fields
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api graphql -f query='
            mutation (
              $project: ID!
              $item: ID!
              $status_field: ID!
              $status_value: String!
              $date_field: ID!
              $date_value: Date!
            ) {
              set_status: updateProjectV2ItemFieldValue(input: {
                projectId: $project
                itemId: $item
                fieldId: $status_field
                value: { 
                  singleSelectOptionId: $status_value
                  }
              }) {
                projectV2Item {
                  id
                  }
              }
              set_date_posted: updateProjectV2ItemFieldValue(input: {
                projectId: $project
                itemId: $item
                fieldId: $date_field
                value: { 
                  date: $date_value
                }
              }) {
                projectV2Item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f item=$ITEM_ID -f status_field=$STATUS_FIELD_ID -f status_value=${{ env.TODO_OPTION_ID }} -f date_field=$DATE_FIELD_ID -f date_value=$DATE --silent

```

</p>
</details> 



I want to use `gh-projects`  where I can easily execute commands:
* List field options for `Select` and `Iteration` fields
* Get items queried by custom field (e.g. not done items, with completed iterations)
* set the new field option for the given item.

Writing this in GraphQL, in yaml, is error-prone. And this is why I see an area where `gh-projects` can help. 

> Options is a property of a field, and as such does not seem to be a core attribute of a Project. I can understand the desire to surface these, but do not feel that it should be its own command, separate from `field-list`. The layout for that command is fixed to keep it consistent, but options could definitely be displayed as part of the existing `json` output.

`Field-list` lists the fields in the project. Would you add a parameter to select an exact one field?

As I explained ☝️ I would like to receive only one field. Getting all fields with their options will force me to manually search for the field I am looking for and then do a second looking for for the option ID.

**Comment by mntlty** [comment]
@mjasion thank you for the context! I'd like to summarize to confirm my understanding:

1. You'd like to be able to get more information from fields, specifically of type SINGLE_SELECT and ITERATION, including the values and IDs of those values. This is not currently available in `gh-projects`
2. You'd like to be able to filter the values from `field-list` based on their name, type, or some other attributes. This is not currently available in `gh-projects` but can be done on the JSON output using another tool, such as jq or node.
3. You'd like to be able to edit the value of a project item, such as an iteration field value. This is not currently available in `gh-projects`, only the `title` field can be updated.

Is that correct?

**Comment by mjasion** [comment]
@mntlty Exactly, thanks for understanding. :-)

I see a lack in the Projects, and implementing those things will improve the experience with projects. Parsing data (from 2nd point) would be nice to have to add in the future

**Comment by mntlty** [comment]
@mjasion thanks for confirming! Here's my proposal for how to proceed:

For the numbered items above:
1. I'd welcome an Issue to discuss adding more JSON details to https://github.com/github/gh-projects/blob/main/format/json.go#L135 for Single Select and Iterations. A concern I have is that there are many complex field types, such as Pull Request and Assignee, and I'm not sure how to best handle the lack of feature parity.
2. More powerful filtering in the extension may be something to add one day, but as of today it's possible to do in a second filter step with `jq` or something similar, and doesn't seem to be worth the cost.
3. I've opened an issue to discuss here https://github.com/github/gh-projects/issues/84

Finally, I would like to close this PR as I don't see `field-list-options` being its own subcommand of `projects`.

**Pull request closed without merging**
